"""Filesystem object storage (single-node local default, docs/ARCHITECTURE.md §5.1)."""

from __future__ import annotations

import asyncio
from pathlib import Path

from app.core.errors import StorageError


class LocalObjectStorage:
    def __init__(self, root: str) -> None:
        self._root = Path(root)

    def _path(self, key: str) -> Path:
        # keys are opaque uuids generated by the caller; reject anything path-like
        if "/" in key or "\\" in key or key in {"", ".", ".."}:
            raise StorageError(f"invalid storage key {key!r}")
        return self._root / key

    async def put(self, key: str, data: bytes, *, content_type: str) -> None:
        def _write() -> None:
            self._root.mkdir(parents=True, exist_ok=True)
            path = self._path(key)
            tmp = path.with_suffix(".tmp")
            tmp.write_bytes(data)
            tmp.replace(path)

        await asyncio.to_thread(_write)

    async def get(self, key: str) -> bytes:
        def _read() -> bytes:
            try:
                return self._path(key).read_bytes()
            except FileNotFoundError as exc:
                raise StorageError(f"object {key!r} not found") from exc

        return await asyncio.to_thread(_read)

    async def delete(self, key: str) -> None:
        def _delete() -> None:
            self._path(key).unlink(missing_ok=True)

        await asyncio.to_thread(_delete)
